I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 276, in script
    $ easy_questions.pop(list(easy_questions.keys())[question_index])
  File "game/script.rpy", line 276, in <module>
    $ easy_questions.pop(list(easy_questions.keys())[question_index])
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 276, in script
    $ easy_questions.pop(list(easy_questions.keys())[question_index])
  File "/home/quertzy/Downloads/renpy-8.2.1-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/quertzy/Downloads/renpy-8.2.1-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 276, in <module>
    $ easy_questions.pop(list(easy_questions.keys())[question_index])
  File "/home/quertzy/Downloads/renpy-8.2.1-sdk/renpy/revertable.py", line 221, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Linux-6.8.4-arch1-1-x86_64-with-glibc2.39 x86_64
Ren'Py 8.2.1.24030407
Learning With You 1.0
Wed Apr 10 21:55:53 2024
